/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author BARO
 */
public class MiniChatClientDlg extends javax.swing.JFrame {

    /**
     * Creates new form MiniChatClientDlg
     */
    private Socket socket;
    private DefaultListModel module;
    private MyInfo info;
    private Thread clientclientthread = null;
    private DataOutputStream streamOut = null;

    public MiniChatClientDlg(MyInfo _info, DefaultListModel _module, Socket _socket) {
        initComponents();
        this.setLocation(500, 300);
        this.setResizable(false);
        this.setVisible(true);
        info = _info;
        jlbMyUsername.setText(info.Username);
        jlbStatus.setText("Online");
        /*Socket*/
        socket = _socket;
        /*Module*/
        module = _module;
        jlUserOnline.setModel(module);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbIcon = new javax.swing.JLabel();
        jlbMyUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlUserOnline = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jlbStatus = new javax.swing.JLabel();
        jlbStatusIcon = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMessenger = new javax.swing.JMenu();
        jDisconnect = new javax.swing.JMenuItem();
        jAbout = new javax.swing.JMenu();
        jmAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dog.png"))); // NOI18N

        jlbMyUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbMyUsername.setText("Username");

        jlUserOnline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlUserOnlineMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlUserOnline);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Userlist");

        jlbStatus.setText("Offline");

        jlbStatusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbIcon)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlbMyUsername)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbStatusIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbStatus)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbMyUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbStatus)
                            .addComponent(jlbStatusIcon)))
                    .addComponent(jlbIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jMessenger.setText("Messenger");

        jDisconnect.setText("Disconnect");
        jDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisconnectActionPerformed(evt);
            }
        });
        jMessenger.add(jDisconnect);

        jMenuBar1.add(jMessenger);

        jAbout.setText("About");

        jmAbout.setText("About");
        jAbout.add(jmAbout);

        jMenuBar1.add(jAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlUserOnlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlUserOnlineMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int index = jlUserOnline.getSelectedIndex();
            String s = (String) module.getElementAt(index);
            Message msg = new Message(s);
            clientclientthread = new ConnectToClient(info, msg);
            clientclientthread.start();
        }
    }//GEN-LAST:event_jlUserOnlineMouseClicked

    private void jDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisconnectActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            streamOut = new DataOutputStream(socket.getOutputStream());
            streamOut.writeBytes("Disconnect");
            streamOut.flush();
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(MiniChatClientDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jDisconnectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            streamOut = new DataOutputStream(socket.getOutputStream());
            streamOut.writeBytes("Disconnect");
            streamOut.flush();
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(MiniChatClientDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAbout;
    private javax.swing.JMenuItem jDisconnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMessenger;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlUserOnline;
    private javax.swing.JLabel jlbIcon;
    private javax.swing.JLabel jlbMyUsername;
    private javax.swing.JLabel jlbStatus;
    private javax.swing.JLabel jlbStatusIcon;
    private javax.swing.JMenuItem jmAbout;
    // End of variables declaration//GEN-END:variables
}
